// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { CreateChatData, CreateChatErrors, CreateChatResponses, GetMessagesChatChatIdGetData, GetMessagesChatChatIdGetErrors, GetMessagesChatChatIdGetResponses, HealthCheckData, HealthCheckResponses, SendChatMessageData, SendChatMessageErrors, SendChatMessageResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Create Chat Session
 */
export const createChat = <ThrowOnError extends boolean = false>(options?: Options<CreateChatData, ThrowOnError>) => (options?.client ?? client).post<CreateChatResponses, CreateChatErrors, ThrowOnError>({ url: '/chat/', ...options });

/**
 * Get Messages
 */
export const getMessagesChatChatIdGet = <ThrowOnError extends boolean = false>(options: Options<GetMessagesChatChatIdGetData, ThrowOnError>) => (options.client ?? client).get<GetMessagesChatChatIdGetResponses, GetMessagesChatChatIdGetErrors, ThrowOnError>({ url: '/chat/{chat_id}', ...options });

/**
 * Message
 */
export const sendChatMessage = <ThrowOnError extends boolean = false>(options: Options<SendChatMessageData, ThrowOnError>) => (options.client ?? client).post<SendChatMessageResponses, SendChatMessageErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/chat/{chat_id}/message',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Health
 */
export const healthCheck = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckResponses, unknown, ThrowOnError>({ url: '/health', ...options });
