// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * BaseResponseSchema
 */
export type BaseResponseSchema = {
    /**
     * Data
     */
    data?: unknown | null;
    /**
     * Message
     */
    message: string;
    /**
     * Success
     */
    success: boolean;
};

/**
 * BaseResponseSchema[UUIDResponse]
 */
export type BaseResponseSchemaUuidResponse = {
    data?: UuidResponse | null;
    /**
     * Message
     */
    message: string;
    /**
     * Success
     */
    success: boolean;
};

/**
 * BaseResponseSchema[list[MessageOut]]
 */
export type BaseResponseSchemaListMessageOut = {
    /**
     * Data
     */
    data?: Array<MessageOut> | null;
    /**
     * Message
     */
    message: string;
    /**
     * Success
     */
    success: boolean;
};

/**
 * Body_send_chat_message
 */
export type BodySendChatMessage = {
    /**
     * Content
     */
    content: string;
    /**
     * File
     */
    file?: Blob | File | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MessageOut
 */
export type MessageOut = {
    /**
     * Content
     */
    content: string;
    role: Role;
    /**
     * File Name
     */
    file_name: string | null;
    /**
     * Chat Id
     */
    chat_id: string;
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * Role
 */
export type Role = 'user' | 'assistant' | 'system';

/**
 * UUIDResponse
 */
export type UuidResponse = {
    /**
     * Id
     */
    id: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type CreateChatData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/chat/';
};

export type CreateChatErrors = {
    /**
     * Bad Request
     */
    400: BaseResponseSchema;
};

export type CreateChatError = CreateChatErrors[keyof CreateChatErrors];

export type CreateChatResponses = {
    /**
     * Successful Response
     */
    201: BaseResponseSchemaUuidResponse;
};

export type CreateChatResponse = CreateChatResponses[keyof CreateChatResponses];

export type GetMessagesChatChatIdGetData = {
    body?: never;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/chat/{chat_id}';
};

export type GetMessagesChatChatIdGetErrors = {
    /**
     * Bad Request
     */
    400: BaseResponseSchema;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMessagesChatChatIdGetError = GetMessagesChatChatIdGetErrors[keyof GetMessagesChatChatIdGetErrors];

export type GetMessagesChatChatIdGetResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseSchemaListMessageOut;
};

export type GetMessagesChatChatIdGetResponse = GetMessagesChatChatIdGetResponses[keyof GetMessagesChatChatIdGetResponses];

export type SendChatMessageData = {
    body: BodySendChatMessage;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/chat/{chat_id}/message';
};

export type SendChatMessageErrors = {
    /**
     * Unsupported Media Type
     */
    415: BaseResponseSchema;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendChatMessageError = SendChatMessageErrors[keyof SendChatMessageErrors];

export type SendChatMessageResponses = {
    /**
     * Successful Response
     */
    201: BaseResponseSchemaListMessageOut;
};

export type SendChatMessageResponse = SendChatMessageResponses[keyof SendChatMessageResponses];

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckResponses = {
    /**
     * Successful Response
     */
    200: BaseResponseSchema;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];
